### PR TITLE
PR: Pin pywinpty version to 1.1.0

### PR DESCRIPTION
**Pull request by andfoy**
Fixes https://github.com/jupyter/terminado/issues/97

### CODE REVIEW

**Comment by blink1073** [comment]
Ah, probably due to a force push

**Comment by blink1073** [comment]
We can squash at the end

**Comment by blink1073** [comment]
We only run the most basic test in [CI on windows](https://github.com/jupyter/terminado/blob/8bae32aed2e6550a4735b2f938d37b5da7a1eed6/.github/workflows/test.yml#L56)

**Comment by andfoy** [comment]
@blink1073 Do the other tests fail here if we try to run them in Windows?

**Comment by blink1073** [comment]
> Do the other tests fail here if we try to run them in Windows?

They already did on the older version of `pywintpy`, which is why we had skipped them originally.

**Comment by andfoy** [comment]
Let me try to run them again, and see if they are still failing, maybe they can explain the failures in the notebook

**Comment by andfoy** [comment]
This permission setting for first time contributors seems to be very unconfortable

**Comment by blink1073** [comment]
> so I don't know if that plays part on the notebook errors

I'm not sure, are you available to test `notebook` against your `pywinpty_1.0.1` branch?

**Comment by blink1073** [comment]
Thanks for fixing those tests!

**Comment by andfoy** [comment]
> I'm not sure, are you available to test notebook against your pywinpty_1.0.1 branch?

The RDP session is still open, so I can try to test it

**Comment by andfoy** [comment]
I got to reproduce the errors locally, it seems that the errors are related to the terminate method, which I don't know what it does underneath and how it interacts with terminado/pywinpty

**Comment by andfoy** [comment]
I did some changes to ptyprocess in https://github.com/spyder-ide/pywinpty/pull/137/files#diff-4a67b83c782a0c2991144686e69d148dc649326c957c603349b7a3d43f8bab18, however, I don't know if those changes broke something? I don't know if removing the `close` method on the PTY object is somewhat involved here

**Comment by blink1073** [comment]
> I don't know if those changes broke something

It appears so, because the terminals are successfully terminated if we pin to the previous version.

**Comment by andfoy** [comment]
@blink1073, could you give us a help there? I touched some of the functionality of ptyprocess, but since you wrote the module, maybe you could verify that is working as expected?

**Review by blink1073 — APPROVED** [review]
Fantastic!

**Comment by stonebig** [comment]
hi, is there a possiblity you can produce a wheel for pypy3.7-v7.3.5-win64 ? it seems a big challenge to me with rust in the middle not happy with PyPy

**Pull request merged**
