### PR TITLE
Make sure that all process output makes it to the terminal

### PR DESCRIPTION
**Pull request by athornton**
The important change is that the terminal would often not print output prior to the first prompt.  This was some combination of the spawned shell process producing output before the PtyWithClients object was there to catch it, and the PtyWithClients object not registered any clients yet.  This PR fixes both of those and addresses https://github.com/jupyterlab/jupyterlab/issues/9023

There are two other classes of changes in here, which are flake8, because I have my editor set up to flake8ify on save.  Those two are replacing the lambdas with inline functions, and the whitespace changes.  If you care, I can go through and reverse those.

### CODE REVIEW

**Comment by athornton** [comment]
https://github.com/jupyter/terminado/pull/76

**Comment by athornton** [comment]
I don't understand the failure in AppVeyor--looks like it succeeded but very slowly?

**Comment by jasongrout** [comment]
Merging and fixing in another PR.

In the future, if you use a branch other than master for your branch, we'd be able to push fixes directly to this.

**Comment by athornton** [comment]
Will do.  I developed it on a ticket branch of mine and then PRed to master in my fork; I can just _not_ do that second thing in the future.  Thanks for the quick response!

**Pull request merged**
