### PR TITLE
Run CI Daily

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
@andfoy it looks like we're unable to import `winpty` after upgrading to 2.0.1, hitting this line[https://github.com/jupyter/terminado/blob/ab4ced0b77c8f198cdc27fe1d52c523635083461/terminado/management.py#L27].

**Comment by andfoy** [comment]
@blink1073, thanks for the heads up, do you know why the wheel is being built up instead of being downloaded from PyPi?

imagen

**Comment by andfoy** [comment]
What happens if the CI is restarted?

**Comment by blink1073** [comment]
Usually they're only built if there is no wheel matching the python version/architecture.  I just kicked the build.

**Comment by andfoy** [comment]
It seems that it tried to build the wheels again, for some reason it is not picking any of these:

imagen

**Comment by blink1073** [comment]
Hmm, it did pick up 3.7.  Let's try again, might be a caching thing.

**Comment by blink1073** [comment]
Back in action, thanks for the consult @andfoy, and congratulations on the release!

**Pull request merged**
