### PR TITLE
Add test for terminating the terminals

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
Heads up @andfoy, it looks like we're not able to properly terminate terminals anymore in `pywinpty 2.0+`.  

```
 >       assert self.single_tm.terminal.ptyproc.closed
E       assert False
```

https://github.com/blink1073/terminado/runs/5162491817?check_suite_focus=true

The [`terminate`](https://github.com/jupyter/terminado/blob/8a8337414b7fc84590985ed1732110fa5fd80da8/terminado/management.py#L87) function is returning `True`, as asserted in the test, but the `ptyproc` is not closing, and not triggering `EOF`.

I'll try and do some more debugging next week.

**Comment by andfoy** [comment]
Thanks for the ping, please let me know if I can help in any way

**Comment by andfoy** [comment]
@blink1073, I've just released pywinpty v2.0.3, it should be available in a few minutes

**Comment by blink1073** [comment]
> I've just released pywinpty v2.0.3, it should be available in a few minutes

Thanks!

**Comment by blink1073** [comment]
@andfoy it works now when I specify using the `WinPTY` backend!

**Pull request merged**
